[package]
name = "trait-set"
version = "0.3.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"
rust-version = "1.56"
repository = "https://github.com/popzxc/trait-set"
documentation = "https://docs.rs/trait-set"
readme = "README.md"
license = "MIT"
keywords = ["trait", "alias", "helpers", "utils"]
categories = ["rust-patterns"]
description = "Support for trait alias feature on stable Rust."

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "=1.0.40"
proc-macro2 = "=1.0.101"

[dev-dependencies]
trybuild = "1.0"
# this is to prevent cargo update from updating to unsupported versions
glob = "=0.3.2"
