[package]
name = "trait-set"
version = "0.3.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"
rust-version = "1.65"
repository = "https://github.com/popzxc/trait-set"
documentation = "https://docs.rs/trait-set"
readme = "README.md"
license = "MIT"
keywords = ["trait", "alias", "helpers", "utils"]
categories = ["rust-patterns"]
description = "Support for trait alias feature on stable Rust."

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "=1.0.41"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "=1.0.90"
# this is to prevent cargo update from updating to unsupported versions
indexmap = "=2.11.4"
toml = "=0.8.20"
toml_datetime = "=0.6.8"
serde_spanned = "=0.6.8"
#syn = "=2.0.106"
